version: "3.9"
volumes:
  vendor-store:
  node_modules-store:
services:
  app:
    command: air
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - './:/go/src/app'
