version: "3.9"
volumes:
  vendor-store:
  node_modules-store:
services:
  app:
    command: go run restapi.go
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - '.:/go/src/app'
