version: "3.9"
volumes:
  vendor-store:
  node_modules-store:
services:
  app:
    command: air
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - './api/out/go:/go/src/app'
