version: "3.9"
services:
  app:
    image: openapitools/openapi-generator-cli:v6.0.1
    command: >
      generate 
        -i /local/docker/openapi-generator/petstone.yaml
        -g go-server
        -o /local/
    volumes:
      - '../../:/local'
